################################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Makefile for the C code which makes up this project.
#
# CREATED:	    12/07/2017
#
# LAST EDITED:	    12/07/2017
###



################################################################################
